export const CHARACTERS_ACTION_TYPES = {
    FETCH_CHARACTERS_START: 'characters/FETCH_CHARACTERS_START',
    FETCH_CHARACTERS_SUCCESS: 'characters/FETCH_CHARACTERS_SUCCESS',
    FETCH_CHARACTERS_FAILED: 'characters/FETCH_CHARACTERS_FAILED',
  };