export const MOVIE_ACTION_TYPES = {
    FETCH_MOVIE_START: 'movie/FETCH_MOVIE_START',
    FETCH_MOVIE_SUCCESS: 'movie/FETCH_MOVIE_SUCCESS',
    FETCH_MOVIE_FAILED: 'movie/FETCH_MOVIE_FAILED',
    RESET_MOVIE_SELECTED: 'movie/RESET_MOVIE_SELECTED',
  };